# Generated by Django 2.1.5 on 2020-12-07 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('designation', models.CharField(max_length=200, verbose_name='Designation')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('linkedin_id', models.CharField(max_length=1000, verbose_name='Linkedin ID')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('job_location', models.CharField(max_length=200, verbose_name='Job Location')),
                ('job_posting_links', models.TextField(verbose_name='Job Posting Links')),
                ('phone_number', models.TextField(max_length=50, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('state', models.CharField(max_length=50, verbose_name='State/Region')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('company_website', models.CharField(max_length=2000, verbose_name='Company Website')),
                ('company_linkedin', models.CharField(max_length=2000, verbose_name='Company Linkedin')),
                ('is_client', models.BooleanField(default=False, verbose_name='Is Client')),
                ('is_dnd', models.BooleanField(default=False, verbose_name='Is DND')),
                ('span', models.IntegerField(default=20, verbose_name='Span')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='Comments')),
                ('response', models.CharField(choices=[('', ''), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Future', 'Future')], default=None, max_length=20, null=True, verbose_name='Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_on', models.DateField(auto_now=True, verbose_name='Created On')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('location', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Location')),
                ('portals', models.CharField(choices=[('', ''), ('Linked In', 'Linked In'), ('Indeed', 'Indeed'), ('Glassdoor', 'Glassdoor'), ('Other', 'Other')], max_length=100)),
                ('is_client', models.BooleanField(default=False, verbose_name='Is Client')),
                ('span', models.IntegerField(default=20, verbose_name='Span')),
                ('is_dnd', models.BooleanField(default=False, verbose_name='Is DND')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now=True, verbose_name='Created On')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='Comments')),
                ('response', models.CharField(choices=[('', ''), ('Positive', 'Positive'), ('Negative', 'Negative'), ('Future', 'Future')], default=None, max_length=20, null=True, verbose_name='Response')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanInDays', models.IntegerField(choices=[(15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60')], default=30)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=100)),
                ('phone2', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('location', models.TextField()),
                ('company_url', models.TextField()),
                ('job_position', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('influencerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Influencers.InfluencerBase')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
            ],
            bases=('Influencers.influencerbase',),
        ),
        migrations.CreateModel(
            name='Influecner',
            fields=[
                ('influencerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Influencers.InfluencerBase')),
                ('is_influencer', models.BooleanField(default=False, verbose_name='Influencer/Prospect')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_ansered', models.BooleanField(default=False, verbose_name='Answered')),
                ('last_contacted_on', models.DateField(verbose_name='Last Contacted Date')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Duplicate?')),
                ('order_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='Order_Number')),
                ('order_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Order Code')),
                ('date_of_promotion', models.DateField(verbose_name='Day of Promotion')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('paid_or_unpaid', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('OK', 'OK')], default=None, max_length=10, null=True, verbose_name='Paid/UnPaid')),
                ('channel_username', models.CharField(max_length=100, verbose_name='Instagram Username')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('collection', models.CharField(max_length=100, null=True, verbose_name='Collection')),
                ('discount_coupon', models.CharField(max_length=100, null=True, verbose_name='Discount code')),
                ('valid_till', models.DateTimeField(verbose_name='Valid Till')),
                ('status', models.CharField(default=None, max_length=30, null=True, verbose_name='Status')),
                ('commission', models.CharField(max_length=10, verbose_name='Fixed Fee/Commission')),
                ('product_cost', models.CharField(max_length=10, verbose_name='Product Cost')),
                ('revenue_analysis', models.CharField(max_length=10, verbose_name='Revenue Analysis')),
                ('revenue_click', models.CharField(max_length=10, verbose_name='Revenue Click')),
                ('comments', models.TextField(blank=True, default='', null=True, verbose_name='Comments')),
            ],
            bases=('Influencers.influencerbase',),
        ),
        migrations.AddField(
            model_name='influencerbase',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='influencerbase',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_name', '-created_at', '-updated_at', 'company_name', '-created_on'], name='Influencers_company_7246ee_idx'),
        ),
        migrations.AddIndex(
            model_name='b2blead',
            index=models.Index(fields=['company_name', '-created_at', '-updated_at', 'company_name', '-created_on'], name='Influencers_company_327862_idx'),
        ),
    ]
