# Generated by Django 2.1.5 on 2020-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influecner',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Reminder1', 'Reminder1'), ('Reminder2', 'Reminder2'), ('Abandoned', 'Abandoned')], default=None, max_length=30, null=True, verbose_name='Status'),
        ),
    ]
