# Generated by Django 2.1.5 on 2020-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='commission',
            field=models.CharField(max_length=10, null=True, verbose_name='Fixed Fee/Commission'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='currency',
            field=models.CharField(max_length=20, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='paid_or_unpaid',
            field=models.CharField(choices=[('', ''), ('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('OK', 'OK')], default=None, max_length=10, null=True, verbose_name='Paid/UnPaid'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='product_cost',
            field=models.FloatField(null=True, verbose_name='Product Cost'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='revenue_analysis',
            field=models.CharField(max_length=10, null=True, verbose_name='Revenue Analysis'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='revenue_click',
            field=models.FloatField(null=True, verbose_name='Revenue Click'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='status',
            field=models.CharField(choices=[('', ''), ('Published', 'Published'), ('Reminder1', 'Reminder1'), ('Reminder2', 'Reminder2'), ('Abandoned', 'Abandoned')], default=None, max_length=30, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='valid_from',
            field=models.DateTimeField(null=True, verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='valid_till',
            field=models.DateTimeField(null=True, verbose_name='Valid Till'),
        ),
    ]
