# Generated by Django 2.1.5 on 2020-12-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0002_auto_20201213_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='date_of_promotion',
            new_name='date_of_promotion_on',
        ),
    ]
