# Generated by Django 2.1.5 on 2020-12-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0003_auto_20201213_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='is_influencer',
            field=models.CharField(choices=[('', ''), ('Prospect', 'Prospect'), ('Influencer', 'Influencer')], max_length=12, verbose_name='Influencer/Prospect'),
        ),
    ]
