# Generated by Django 2.1.5 on 2020-12-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0004_auto_20201213_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='is_answered',
            field=models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=5, verbose_name='Answered'),
        ),
    ]
