# Generated by Django 2.1.5 on 2020-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0007_auto_20201213_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='revenue_analysis',
            field=models.FloatField(null=True, verbose_name='Revenue Analysis'),
        ),
    ]
