# Generated by Django 2.1.5 on 2020-12-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0008_auto_20201214_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2blead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='LeadSpan',
        ),
        migrations.RemoveField(
            model_name='masterlead',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='B2BLead',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='MasterLead',
        ),
    ]
