# Generated by Django 2.1.5 on 2020-12-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0010_auto_20201217_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='channel',
            field=models.CharField(max_length=2000, null=True, verbose_name='Channel'),
        ),
    ]
