# Generated by Django 2.1.5 on 2021-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0013_auto_20201221_0903'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='influencer',
            name='Influencers_email_7fa304_idx',
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_old_order',
            field=models.BooleanField(default=False, verbose_name='Is Old Order?'),
        ),
        migrations.AddIndex(
            model_name='influencer',
            index=models.Index(fields=['email', 'channel_username', '-valid_from'], name='Influencers_email_c5889b_idx'),
        ),
    ]
