# Generated by Django 2.1.5 on 2021-01-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0014_auto_20210104_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='is_old_order',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Old Order?'),
        ),
    ]
