# Generated by Django 2.1.5 on 2021-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0015_auto_20210104_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='revenue_click',
            field=models.FloatField(default=0, null=True, verbose_name='Revenue Click'),
        ),
    ]
