# Generated by Django 2.1.5 on 2021-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0016_auto_20210104_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='order_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order Code'),
        ),
    ]
