# Generated by Django 2.1.5 on 2021-01-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0018_auto_20210117_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerbase',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
    ]
