# Generated by Django 2.1.5 on 2021-01-17 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0019_auto_20210117_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerbase',
            name='centra_update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 20, 43, 27, 540042, tzinfo=utc), verbose_name='Centra Update At'),
            preserve_default=False,
        ),
    ]
