# Generated by Django 2.1.5 on 2021-01-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0021_auto_20210118_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerbase',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Updated At'),
        ),
    ]
