# Generated by Django 2.1.5 on 2021-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0023_auto_20210120_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerbase',
            name='centra_orders_update_at',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='revenue_analysis',
            field=models.FloatField(default=0, null=True, verbose_name='Revenue Analysis'),
        ),
    ]
