# Generated by Django 2.1.5 on 2021-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0024_auto_20210121_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('orderDate', models.DateTimeField()),
                ('discount_coupons', models.CharField(max_length=100)),
                ('grandTotal', models.FloatField()),
                ('status', models.CharField(choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
    ]
