# Generated by Django 2.1.5 on 2021-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0027_orderinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='discount_coupons',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
