# Generated by Django 2.1.5 on 2021-02-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0028_auto_20210129_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='paid_or_unpaid',
            field=models.CharField(blank=True, choices=[('', ''), ('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('ÖK', 'ÖK')], default=None, max_length=10, null=True, verbose_name='Paid/UnPaid'),
        ),
    ]
