# Generated by Django 2.1.5 on 2021-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0029_auto_20210205_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='is_influencer',
            field=models.CharField(choices=[('', ''), ('Prospect', 'Prospect'), ('Influencer', 'Influencer'), ('PR', 'PR')], max_length=12, verbose_name='Influencer/Prospect'),
        ),
    ]
