# Generated by Django 2.1.5 on 2021-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0030_auto_20210205_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='is_influencer',
            field=models.CharField(choices=[('', ''), ('Prospect', 'Prospect'), ('Influencer', 'Influencer'), ('PR_', 'PR_')], max_length=12, verbose_name='Influencer/Prospect'),
        ),
    ]
