# Generated by Django 2.1.5 on 2021-02-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0031_auto_20210206_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrefernces',
            fields=[
                ('influencerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Influencers.InfluencerBase')),
                ('influe_field_preferences', models.TextField(verbose_name='Influencer Field Preferences')),
            ],
            bases=('Influencers.influencerbase',),
        ),
    ]
