# Generated by Django 2.1.5 on 2021-02-06 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Influencers', '0032_userprefernces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPrefernces',
            new_name='UserPreferences',
        ),
    ]
