# Generated by Django 2.1.5 on 2021-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0033_auto_20210206_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=10)),
                ('continent', models.CharField(max_length=20)),
                ('isEU', models.BooleanField()),
            ],
        ),
    ]
