# Generated by Django 2.1.5 on 2021-02-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0034_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_of_order', to='Influencers.Country'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='order_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order Number'),
        ),
    ]
