# Generated by Django 2.1.5 on 2021-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0036_auto_20210211_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='country',
            field=models.CharField(default='india', max_length=70),
            preserve_default=False,
        ),
    ]
