# Generated by Django 2.1.5 on 2021-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0037_auto_20210212_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='commission',
            field=models.FloatField(max_length=10, null=True, verbose_name='Fixed Fee/Commission'),
        ),
    ]
