# Generated by Django 2.1.5 on 2021-02-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0038_auto_20210212_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='commission',
            field=models.FloatField(default=0, max_length=10, null=True, verbose_name='Fixed Fee/Commission'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='product_cost',
            field=models.FloatField(default=0, null=True, verbose_name='Product Cost'),
        ),
    ]
