# Generated by Django 2.1.5 on 2021-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0039_auto_20210213_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='discount_coupon',
            field=models.CharField(max_length=100, null=True, verbose_name='Discount Code'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='paid_or_unpaid',
            field=models.CharField(blank=True, choices=[('', ''), ('Paid', 'Paid'), ('UnPaid', 'UnPaid'), ('ÖK', 'ÖK')], default=None, max_length=10, null=True, verbose_name='Paid/Unpaid"'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='grandTotal',
            field=models.FloatField(default=0),
        ),
    ]
