# Generated by Django 2.1.5 on 2021-02-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0040_auto_20210216_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='paid_or_unpaid',
            field=models.CharField(blank=True, choices=[('', ''), ('Paid', 'Paid'), ('UnPaid', 'UnPaid'), ('ÖK', 'ÖK')], default=None, max_length=10, null=True, verbose_name='Paid/Unpaid'),
        ),
    ]
