# Generated by Django 2.1.5 on 2021-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0042_auto_20210222_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
