# Generated by Django 2.1.5 on 2021-02-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0044_auto_20210224_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='collection',
            field=models.CharField(max_length=100, null=True, verbose_name='Campaign'),
        ),
    ]
