# Generated by Django 2.1.5 on 2021-02-28 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Influencers', '0045_auto_20210224_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='managed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
    ]
