# Generated by Django 2.1.5 on 2021-02-28 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0046_influencer_managed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='managed_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='managed_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
            preserve_default=False,
        ),
    ]
