# Generated by Django 2.1.5 on 2021-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencers', '0048_auto_20210301_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='date_of_promotion_at',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
    ]
