#!/bin/bash

#kills and creates new tasks
curl http://localhost:8000/resetCentra
#curl  http://localhost:8000/updateCentraValidations
curl  http://localhost:8000/centraToDB
#start running scheduled tasks
exec python manage.py process_tasks